[package]
name = "glance-core"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["from"] }
image = "0.25.6"
minifb = { version = "0.28.0", features = ["wayland"] }
rayon = "1.10.0"
